#!/bin/csh
#
# This copies a distribution to be put into ACL (& Composer, etc)
#  to make an MIT ready distribution, see jdi
#
umask 002

set dir=/scm/clx/4.1

rm -rf $dir
mkdir $dir
cp -p CHANGES NEWCHANGES README Makefile TAGS $dir
tar cf - *.c *.cl MITdist demo/*.cl demo/README debug/*.cl test/*.cl doc | \
	(cd $dir;tar xf -)
find $dir -type f -print | xargs chmod ugo-w
